### ISSUE TITLE
issue with vararg param in ga:message_on_number_deployed

### ISSUE THREAD

**Issue by chadvandy** [chadvandy/tw_autogen#10]

**Comment by paperpancake** [comment]
`battle_manager:get_spawn_zone_collection_by_name` also has a vararg issue. (My pull request addresses this with an override, but I thought I'd mention it here in case an automated solution is in the works.)

**Comment by paperpancake** [comment]
> `battle_manager:get_spawn_zone_collection_by_name` also has a vararg issue. (My pull request addresses this with an override, but I thought I'd mention it here in case an automated solution is in the works.)

I'm not as smart as I thought I was. My override did not fix the vararg issue for this method. It just made the variable arguments disappear altogether somehow.
