### ISSUE TITLE
Functions use ":" even though some should use "."

### ISSUE THREAD

**Issue by paperpancake** [chadvandy/tw_autogen#12]
Some functions like those in [common](https://chadvandy.github.io/tw_modding_resources/WH3/battle/common.html), [wh3/battle/common.lua](https://github.com/chadvandy/tw_autogen/tree/main/output/wh3/battle/common.lua) and [validate](https://chadvandy.github.io/tw_modding_resources/WH3/battle/validate.html), [wh3/battle/validate.lua](https://github.com/chadvandy/tw_autogen/tree/main/output/wh3/battle/common.lua) should use "." instead of ":". These are generated files.

With ":", Lua passes in `self` as the first argument. So currently we get cryptic warnings like "the function received at least 3 arguments, but got 2" when using these functions correctly.

**Comment by chadvandy** [comment]
Yes good catch! Thought I fixed this earlier, thank you for pointing it out.

**Comment by chadvandy** [comment]
handled in the last commit
