### ISSUE TITLE
enable optional args ie. `---@param name type?`

### ISSUE THREAD

**Issue by chadvandy** [chadvandy/tw_autogen#13]

**Comment by paperpancake** [comment]
To be ~~pedantic~~ precise, it should be `---@param name? type`, according to the examples [here](https://github.com/sumneko/lua-language-server/wiki/EmmyLua-Annotations#optional-params).

**Comment by chadvandy** [comment]
they work either way

**Comment by chadvandy** [comment]
query the HTML files for "optional,default value="
