### ISSUE TITLE
Latest commit misreads events as return values

### ISSUE THREAD

**Issue by paperpancake** [chadvandy/tw_autogen#22]
This issue is new in commit [b1f747a (links to the diff)](https://github.com/chadvandy/tw_autogen/commit/b1f747a032fd6bf5356b927b0b09143172e2628f#diff-edece8bb11e75499734b6a292985f6f52d9ca9d5ca9fddaf927db13be0de3e30R741)

In [battle_manager](https://github.com/chadvandy/tw_autogen/blob/e978e5307ceda3300f01cbdb71eb59de6348fc90/output/wh3/battle/battle_manager.lua), many incorrect return values with undefined types are being added to [get_camera_distance_travelled](https://chadvandy.github.io/tw_modding_resources/WH3/battle/battle_manager.html#function:battle_manager:get_camera_distance_travelled). These come from a list in the Engagement Monitor documentation that comes right after that function in the html file for battle_manager.

**Comment by chadvandy** [comment]
good catch - I manually removed this before but that got overwritten. It's the issue from #8 that I have to figure out later
